#!/usr/bin/env python3
"""
brain_update.py — regenerate the LIVE STATE section of BRAIN.md from the bot's
actual state (mirror JSON + baseline). Runs via launchd com.aryan.polymarket-brain
every 30 min. Curated sections above the AUTO markers are never touched.
"""
import json, os, subprocess, sys, time
from datetime import datetime, timezone

BASE  = os.path.dirname(os.path.abspath(__file__))
BRAIN = os.path.join(BASE, "BRAIN.md")
STATE = os.path.join(BASE, "scalp_lab_state.json")
BASEF = os.path.join(BASE, "pnl_baseline.json")

FOCUS = ["nearres", "sportres", "nearreslow", "nearresfade", "ytbuzz",
         "nohappen", "longshortbias", "clobimbal", "polyflup", "noevent",
         "newsno", "btc15no", "weatherno", "fogbuy", "crashbuy", "polvol",
         "latefade", "vlrtop", "gtrend", "bookpress", "kellyfav", "newslag",
         "midfield",
         # 2026-06-11 batch: structural/arb legs
         "wcmatch", "famsum", "mapdown", "ladderarb", "thetadk",
         "certsnipe", "dipladder", "clusterarb", "socspread", "peacefwd"]
CONTROLS = ["allin", "coinflip"]

def leg_line(leg, b, base):
    pr = [r for r in b.get("closed", []) if r.get("pnl_usdc") is not None]
    op = len(b.get("open", []))
    if not pr and not op:
        return None
    w  = [r for r in pr if r["pnl_usdc"] > 0]
    l  = [r for r in pr if r["pnl_usdc"] < 0]
    aw = sum(r["pnl_usdc"] for r in w) / len(w) if w else 0
    al = abs(sum(r["pnl_usdc"] for r in l) / len(l)) if l else 0
    pnl = sum(r["pnl_usdc"] for r in pr) - base.get(leg, 0)
    wr = f"{len(w)/len(pr)*100:3.0f}%" if pr else "  — "
    rr = f"{aw/al:4.1f}" if al else (" inf" if w else "  — ")
    return f"| {leg} | {len(pr)} | {op} | {wr} | {rr} | {pnl:+.2f} |"

def main():
    state = json.load(open(STATE))
    age = time.time() - os.path.getmtime(STATE)
    try:
        base = json.load(open(BASEF)).get("baseline", {})
    except Exception:
        base = {}

    lines = [
        "<!-- AUTO:BEGIN — everything below is regenerated by brain_update.py -->",
        "## LIVE STATE (auto)",
        f"Updated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} · "
        f"mirror age {age:.0f}s {'(healthy)' if age < 300 else '(STALE — check watchdog)'}",
        "",
        "| leg | exits | open | WR | R:R | P&L since reset |",
        "|---|---|---|---|---|---|",
    ]
    for leg in FOCUS:
        row = leg_line(leg, state.get(leg, {}), base)
        if row:
            lines.append(row)

    # gate + controls — gate counts CONFIG-CONSISTENT exits only (entry_fill
    # ≤ 0.965, i.e. trades today's 0.95 cap would still take). Validation
    # 2026-06-11: mixed-era count was 24 but only 12 match the live config.
    nr = [r for r in state.get("nearres", {}).get("closed", [])
          if r.get("pnl_usdc") is not None
          and r.get("entry_fill") is not None and float(r["entry_fill"]) <= 0.965]
    ctrl = sum(r["pnl_usdc"] for lg in CONTROLS
               for r in state.get(lg, {}).get("closed", [])
               if r.get("pnl_usdc") is not None)
    # ── watchdog / process health ──────────────────────────────────────────
    wd_alive = subprocess.run(["pgrep", "-f", "watchdog_loop.sh"],
                              capture_output=True).returncode == 0
    stray = subprocess.run(["pgrep", "-f", "scalp_lab.py run"],
                           capture_output=True).returncode == 0
    wd_last, wd_fails = "(no log)", 0
    try:
        wd_lines = open(os.path.join(BASE, "watchdog.log")).readlines()[-20:]
        wd_last  = wd_lines[-1].strip() if wd_lines else "(empty)"
        wd_fails = sum(1 for l in wd_lines if "failed" in l or "NOT refreshing" in l)
    except Exception:
        pass

    lines += [
        "",
        "### Health",
        f"- watchdog_loop.sh: {'RUNNING ✓' if wd_alive else 'DOWN ✗ — relaunch: nohup bash watchdog_loop.sh &'}",
        f"- stray run-mode bots: {'PRESENT ✗ — kill them (race Postgres)' if stray else 'none ✓'}",
        f"- watchdog last: `{wd_last}`",
        f"- failures in last 20 watchdog lines: {wd_fails}",
        "",
        f"- **nearres gate: {len(nr)}/30 config-consistent exits** "
        f"(selection-corrected significance still pending — best-of-90-legs "
        f"means raw CI>0 happens ~90% of the time by luck; DSR at n=30)",
        f"- Controls lifetime: ${ctrl:+.2f} "
        f"{'(negative — marking honest ✓)' if ctrl < 0 else '(POSITIVE — MARKING BUG!)'}",
        f"- Open positions (focus legs): "
        f"{sum(len(state.get(l, {}).get('open', [])) for l in FOCUS)}",
    ]
    # 24/7 OOS backtest summary (backtest_nearres.py via launchd, every 2h)
    try:
        bs = json.load(open(os.path.join(BASE, "backtest_summary.json")))
        lines.append(f"- OOS backtest ({bs.get('updated','?')}, "
                     f"{bs.get('markets_processed',0)} resolved markets):")
        for band, d in bs.get("bands", {}).items():
            sig = "CI>0 ✓" if d["ci_lo"] > 0 else "CI incl. 0"
            lines.append(f"  - {band}: n={d['n']} wr={d['wr']}% "
                         f"pnl=${d['pnl']:+.2f} [{d['ci_lo']},{d['ci_hi']}] {sig}")
    except Exception:
        lines.append("- OOS backtest: no summary yet")
    # macro market board (market_indices.py covariate — CONTEXT only, not a signal)
    try:
        import market_indices
        lines += ["", "### Markets", f"- {market_indices.summary_line()}"]
    except Exception:
        pass
    lines += [
        "<!-- AUTO:END -->",
    ]

    brain = open(BRAIN).read()
    b0 = brain.index("<!-- AUTO:BEGIN")
    b1 = brain.index("<!-- AUTO:END -->") + len("<!-- AUTO:END -->")
    out = brain[:b0] + "\n".join(lines) + brain[b1:]
    tmp = BRAIN + ".tmp"
    with open(tmp, "w") as f:
        f.write(out)
    os.replace(tmp, BRAIN)
    print("BRAIN.md live state refreshed")

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
