"""data_sources.py — registry of 166 KEYLESS data sources for the Polymarket bot.

Every source was LIVE-curl-validated (HTTP 2xx, real content, NO key/auth) on 2026-06-21
by the data-sources-100 workflow. Keyless-first is the house rule — these need no API
key, signup, or auth header. Consumed by geo-intel (multi-source intel), the news legs,
and any analyst/data-gate that wants broad keyless coverage.

Usage:
    import data_sources as ds
    ds.SOURCES                      # list of dicts: name, url, category, type, provides
    ds.by_category("crypto")        # sources in one category
    ds.categories()                 # {category: count}
    ds.fetch(name_or_url)           # keyless GET -> bytes (urllib, 10s timeout)
    python3 data_sources.py         # print the registry summary
Read-only. Paper research. No keys, no funds.
"""
import urllib.request, json as _json

SOURCES = [
    {"name": 'FT Commodities RSS', "url": 'https://r.jina.ai/https://www.ft.com/commodities?format=rss', "category": 'commodities', "type": 'rss', "provides": 'Financial Times commodities-section headlines as RSS (keyless feed; article bodies paywalled). Commodity macro headlines.'},
    {"name": 'Investing.com — Commodities news RSS', "url": 'https://r.jina.ai/https://www.investing.com/rss/news_11.rss', "category": 'commodities', "type": 'rss', "provides": 'Dedicated commodities news feed (metals, energy, ags). Independent commodity headline source.'},
    {"name": 'EIA — Today in Energy RSS', "url": 'https://r.jina.ai/https://www.eia.gov/rss/todayinenergy.xml', "category": 'commodities/energy', "type": 'rss', "provides": 'US EIA daily energy analysis (oil, gas, prices, supply). Keyless commodity-fundamentals feed.'},
    {"name": 'OilPrice.com — main RSS', "url": 'https://r.jina.ai/https://oilprice.com/rss/main', "category": 'commodities/energy', "type": 'rss', "provides": 'Crude oil, gas, and energy-commodity market news and price commentary. Oil-market event feed.'},
    {"name": 'Alternative.me — Fear & Greed index', "url": 'https://r.jina.ai/https://api.alternative.me/fng/?limit=30', "category": 'crypto', "type": 'json', "provides": 'Daily crypto Fear & Greed value + classification (0-100). Powers the feargreed contrarian leg (cached 1h).'},
    {"name": 'Binance Futures — open interest history', "url": 'https://r.jina.ai/https://fapi.binance.com/futures/data/openInterestHist?symbol=BTCUSDT&period=1h&limit=24', "category": 'crypto', "type": 'json', "provides": 'Historical open interest (contracts + USD value) by interval. Positioning/leverage build-up signal for crypto direction legs.'},
    {"name": 'Binance Futures — premium index / funding', "url": 'https://r.jina.ai/https://fapi.binance.com/fapi/v1/premiumIndex?symbol=BTCUSDT', "category": 'crypto', "type": 'json', "provides": 'Mark price, index price, last funding rate, next funding time for perps. Funding/basis signal (perp-funding-basis leg).'},
    {"name": 'Binance — 24h ticker (spot)', "url": 'https://r.jina.ai/https://api.binance.com/api/v3/ticker/24hr?symbol=BTCUSDT', "category": 'crypto', "type": 'json', "provides": '24h high/low/open/last/volume/weighted-avg for any spot pair. Deepest-liquidity reference price for marking crypto markets.'},
    {"name": 'Binance — klines/candles', "url": 'https://r.jina.ai/https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1h&limit=24', "category": 'crypto', "type": 'json', "provides": 'OHLCV candles at any interval (1m..1d). No-lookahead candle->forward-return feed for the candle knowledge logger.'},
    {"name": 'Bitfinex — ticker (v2)', "url": 'https://r.jina.ai/https://api-pub.bitfinex.com/v2/ticker/tBTCUSD', "category": 'crypto', "type": 'json', "provides": 'Compact array: bid/ask/daily-change/last/volume/high/low. Another keyless venue for cross-venue dispersion.'},
    {"name": 'Bitstamp — ticker', "url": 'https://r.jina.ai/https://www.bitstamp.net/api/v2/ticker/btcusd/', "category": 'crypto', "type": 'json', "provides": 'Last/bid/ask/high/low/volume/VWAP on a long-running EU exchange. Extra cross-venue price for xvenue logger.'},
    {"name": 'Blockchain.com charts — market price (JSON)', "url": 'https://api.blockchain.info/charts/market-price?timespan=5days&format=json', "category": 'crypto', "type": 'json', "provides": 'Time-series of BTC market price (and other chart names: hash-rate, n-transactions, difficulty). Historical on-chain/price series, no key.'},
    {"name": 'Blockchain.info — multi-currency ticker', "url": 'https://blockchain.info/ticker', "category": 'crypto', "type": 'json', "provides": 'BTC price in many fiat currencies (15m/last/buy/sell). Simple keyless fiat-conversion + price reference.'},
    {"name": 'Blockchair — bitcoin stats', "url": 'https://api.blockchair.com/bitcoin/stats', "category": 'crypto', "type": 'json', "provides": 'Blocks, transactions, mempool size, hashrate, difficulty, market price/cap, dominance. Broad on-chain network dashboard in one call.'},
    {"name": 'CoinDesk — RSS', "url": 'https://www.coindesk.com/arc/outboundfeeds/rss', "category": 'crypto', "type": 'rss', "provides": 'Major crypto news headlines. Second news feed to corroborate/diversify event signals.'},
    {"name": 'CoinGecko — coins markets (top by mcap)', "url": 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=50&page=1', "category": 'crypto', "type": 'json', "provides": 'Ranked market data for top coins: price, 24h/7d change, market cap, volume, ATH. Broad market snapshot for crypto Up/Down legs.'},
    {"name": 'CoinGecko — simple price', "url": 'https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,solana&vs_currencies=usd&include_24hr_change=true', "category": 'crypto', "type": 'json', "provides": 'Fast spot USD price + 24h change for named coins. Cheap polling source for diverg/spot-vs-Polymarket divergence signal.'},
    {"name": 'CoinLore — tickers', "url": 'https://api.coinlore.net/api/tickers/?start=0&limit=50', "category": 'crypto', "type": 'json', "provides": 'Keyless price/volume/mcap/supply + rank for thousands of coins. Backup aggregate when CoinGecko rate-limits.'},
    {"name": 'CoinPaprika — tickers', "url": 'https://api.coinpaprika.com/v1/tickers?limit=50', "category": 'crypto', "type": 'json', "provides": 'Keyless price/volume/mcap/circulating-supply for top coins. Independent second source to cross-check CoinGecko (avoid single-feed bias).'},
    {"name": 'Coinbase Exchange — product ticker', "url": 'https://api.exchange.coinbase.com/products/BTC-USD/ticker', "category": 'crypto', "type": 'json', "provides": 'Best bid/ask, last price, 24h volume from Coinbase order book. Third independent price feed for marking/divergence.'},
    {"name": 'Coinbase — spot price (consumer API)', "url": 'https://api.coinbase.com/v2/prices/BTC-USD/spot', "category": 'crypto', "type": 'json', "provides": 'Simple keyless spot price; also supports buy/sell. Lightweight redundancy for price fetch.'},
    {"name": 'Cointelegraph — RSS', "url": 'https://cointelegraph.com/rss', "category": 'crypto', "type": 'rss', "provides": 'Headlines for crypto news/regulation/markets. News-impact and event detection for crypto markets (crypto-news-impact leg).'},
    {"name": 'CryptoSlate — RSS', "url": 'https://cryptoslate.com/feed/', "category": 'crypto', "type": 'rss', "provides": 'Crypto markets/DeFi/regulation headlines. Breadth source for news-flow sentiment.'},
    {"name": 'Decrypt — RSS', "url": 'https://decrypt.co/feed', "category": 'crypto', "type": 'rss', "provides": 'Crypto + Web3 news headlines. Additional event-stream coverage, keyless.'},
    {"name": 'DefiLlama — chains TVL', "url": 'https://api.llama.fi/v2/chains', "category": 'crypto', "type": 'json', "provides": 'Aggregate TVL per chain (Ethereum, Solana, etc.). Chain-rotation / liquidity-migration signal.'},
    {"name": 'DefiLlama — protocols TVL', "url": 'https://api.llama.fi/protocols', "category": 'crypto', "type": 'json', "provides": 'TVL, 1d/7d change, chain, category for every DeFi protocol. Capital-flow / risk-appetite gauge across DeFi.'},
    {"name": 'DefiLlama — stablecoins (with prices)', "url": 'https://stablecoins.llama.fi/stablecoins?includePrices=true', "category": 'crypto', "type": 'json', "provides": 'Circulating supply, peg price, chain breakdown per stablecoin. Stablecoin-flow / depeg-watch and liquidity proxy.'},
    {"name": 'DefiLlama — yields pools', "url": 'https://yields.llama.fi/pools', "category": 'crypto', "type": 'json', "provides": 'APY, TVL, project, chain for DeFi yield pools. Yield-regime and risk-appetite context.'},
    {"name": 'Gemini — pubticker', "url": 'https://api.gemini.com/v1/pubticker/btcusd', "category": 'crypto', "type": 'json', "provides": 'Bid/ask/last/24h volume from a regulated US exchange. Cross-venue spread/dispersion input.'},
    {"name": 'Kraken — OHLC candles', "url": 'https://api.kraken.com/0/public/OHLC?pair=XBTUSD&interval=60', "category": 'crypto', "type": 'json', "provides": 'OHLCV candles (interval in minutes) with last-since cursor. Backup candle source / ccxt fallback for candle logger.'},
    {"name": 'Kraken — ticker', "url": 'https://r.jina.ai/https://api.kraken.com/0/public/Ticker?pair=XBTUSD', "category": 'crypto', "type": 'json', "provides": 'Bid/ask/last/VWAP/volume/high-low for Kraken pairs. US-accessible exchange cross-check, robust when Binance is geo-blocked.'},
    {"name": 'OKX — market ticker', "url": 'https://r.jina.ai/https://www.okx.com/api/v5/market/ticker?instId=BTC-USDT', "category": 'crypto', "type": 'json', "provides": 'Last/bid/ask/24h OHLCV for spot or swap instIds. Asia-liquidity venue, adds to cross-venue funding/price set.'},
    {"name": 'mempool.space — difficulty adjustment', "url": 'https://r.jina.ai/https://mempool.space/api/v1/difficulty-adjustment', "category": 'crypto', "type": 'json', "provides": 'Progress %, estimated change, remaining blocks/time to next BTC difficulty epoch. Useful for difficulty/hashrate prediction markets.'},
    {"name": 'mempool.space — recommended fees', "url": 'https://r.jina.ai/https://mempool.space/api/v1/fees/recommended', "category": 'crypto', "type": 'json', "provides": 'Current BTC fee estimates (fastest/half-hour/hour sat/vB). On-chain congestion / network-stress signal, keyless.'},
    {"name": 'OpenDota Leagues', "url": 'https://api.opendota.com/api/leagues', "category": 'esports', "type": 'json', "provides": 'Dota 2 league/tournament list with tiers and IDs. Keyless.'},
    {"name": 'OpenDota Live Matches', "url": 'https://api.opendota.com/api/live', "category": 'esports', "type": 'json', "provides": 'Currently live high-MMR/pro Dota 2 games with scores and game time. Keyless.'},
    {"name": 'OpenDota Pro Matches (Dota 2 esports)', "url": 'https://api.opendota.com/api/proMatches', "category": 'esports', "type": 'json', "provides": 'Recent professional Dota 2 matches: teams, league, winner, match IDs. Keyless free tier.'},
    {"name": 'OpenDota Teams', "url": 'https://r.jina.ai/https://api.opendota.com/api/teams', "category": 'esports', "type": 'json', "provides": 'Dota 2 pro team rankings, ratings, win/loss. Keyless reference for esports favorites.'},
    {"name": 'VLR.gg Valorant News RSS', "url": 'https://www.vlr.gg/rss/news/', "category": 'esports', "type": 'rss', "provides": 'Valorant esports news/match-result headlines as RSS. Keyless, no signup.'},
    {"name": 'BBC Business/Economy RSS', "url": 'https://feeds.bbci.co.uk/news/business/economy/rss.xml', "category": 'general aggregator', "type": 'rss', "provides": 'BBC economy/business headlines — reliable keyless general-macro feed for cross-checking events.'},
    {"name": 'Bing News RSS (search query)', "url": 'https://www.bing.com/news/search?q=commodities&format=rss', "category": 'general aggregator', "type": 'rss', "provides": 'Keyword news search as RSS; second independent aggregator vs Google News.'},
    {"name": 'Google News RSS (search query)', "url": 'https://news.google.com/rss/search?q=shipping+freight+chokepoint&hl=en-US&gl=US&ceid=US:en', "category": 'general aggregator', "type": 'rss', "provides": 'Arbitrary keyword news aggregation as RSS (change q= for any topic).'},
    {"name": 'HNRSS — Hacker News front page RSS', "url": 'https://hnrss.org/frontpage', "category": 'general aggregator', "type": 'rss', "provides": 'Hacker News front page as RSS (also /newest and ?q= feeds).'},
    {"name": 'Hacker News (Algolia Search API)', "url": 'https://hn.algolia.com/api/v1/search_by_date?query=shipping&tags=story', "category": 'general aggregator', "type": 'json', "provides": 'Full-text, time-sorted search over HN stories/comments in JSON.'},
    {"name": 'Wikipedia Current Events Portal (MediaWiki API)', "url": 'https://en.wikipedia.org/w/api.php?action=parse&page=Portal:Current_events&format=json', "category": 'general aggregator', "type": 'api', "provides": 'Structured daily world-events digest via the keyless MediaWiki parse API.'},
    {"name": 'Al Jazeera - All News', "url": 'https://www.aljazeera.com/xml/rss/all.xml', "category": 'geopolitics/world news', "type": 'rss', "provides": 'Full Al Jazeera English news feed with strong Middle East, Africa and Global South geopolitical coverage.'},
    {"name": 'BBC News - World', "url": 'https://feeds.bbci.co.uk/news/world/rss.xml', "category": 'geopolitics/world news', "type": 'rss', "provides": 'Top global news headlines and world affairs from BBC, updated continuously; broad geopolitical coverage.'},
    {"name": 'China Digital Times', "url": 'https://chinadigitaltimes.net/feed/', "category": 'geopolitics/world news', "type": 'rss', "provides": 'China-focused politics, censorship, and foreign-policy news; useful for China/Taiwan/Asia geopolitics signals.'},
    {"name": 'Der Spiegel International (English)', "url": 'https://www.spiegel.de/international/index.rss', "category": 'geopolitics/world news', "type": 'rss', "provides": 'Spiegel International English feed; in-depth European and global affairs analysis.'},
    {"name": 'Deutsche Welle - World (English)', "url": 'https://rss.dw.com/rdf/rss-en-world', "category": 'geopolitics/world news', "type": 'rss', "provides": 'DW English world news; European and global affairs from a German public broadcaster.'},
    {"name": 'Fox News - World', "url": 'https://moxie.foxnews.com/google-publisher/world.xml', "category": 'geopolitics/world news', "type": 'rss', "provides": 'Fox News world section; US-angle international and conflict headlines for sentiment/breadth.'},
    {"name": 'France 24 - English', "url": 'https://www.france24.com/en/rss', "category": 'geopolitics/world news', "type": 'rss', "provides": 'France 24 English headlines; strong coverage of Europe, Africa, and Francophone-region geopolitics.'},
    {"name": 'GDACS Global Disaster Alerts', "url": 'https://gdacs.org/xml/rss.xml', "category": 'geopolitics/world news', "type": 'rss', "provides": 'Global Disaster Alert and Coordination System; real-time alerts on earthquakes, cyclones, floods, conflicts impact.'},
    {"name": 'Kyiv Independent', "url": 'https://kyivindependent.com/feed/rss/', "category": 'geopolitics/world news', "type": 'rss', "provides": 'English-language Ukraine war and Eastern Europe coverage; front-line, sanctions, and Russia developments.'},
    {"name": 'Kyiv Post', "url": 'https://www.kyivpost.com/feed', "category": 'geopolitics/world news', "type": 'rss', "provides": 'Ukraine news outlet; war updates, politics, and regional geopolitics.'},
    {"name": 'Lawfare', "url": 'https://www.lawfaremedia.org/feeds/articles', "category": 'geopolitics/world news', "type": 'rss', "provides": 'National-security, international law, and conflict analysis; sanctions, war powers, and geopolitics commentary.'},
    {"name": 'NHK (Japan) News - International', "url": 'https://www3.nhk.or.jp/rss/news/cat6.xml', "category": 'geopolitics/world news', "type": 'rss', "provides": 'NHK Japanese public broadcaster international news feed; strong Asia-Pacific and East Asia geopolitical coverage.'},
    {"name": 'NPR World News', "url": 'https://feeds.npr.org/1004/rss.xml', "category": 'geopolitics/world news', "type": 'rss', "provides": 'NPR world desk; US-perspective international news, conflicts, and diplomacy.'},
    {"name": 'ReliefWeb Updates', "url": 'https://reliefweb.int/updates/rss.xml', "category": 'geopolitics/world news', "type": 'rss', "provides": 'OCHA-run humanitarian feed; situation reports on conflicts, disasters, and emergencies worldwide.'},
    {"name": 'The Guardian - World', "url": 'https://www.theguardian.com/world/rss', "category": 'geopolitics/world news', "type": 'rss', "provides": 'Guardian world-news section feed; international politics, conflict and diplomacy stories.'},
    {"name": 'The Jerusalem Post - Front Page', "url": 'https://www.jpost.com/rss/rssfeedsfrontpage.aspx', "category": 'geopolitics/world news', "type": 'rss', "provides": 'Front-page feed covering Israel, Iran, Gaza, and broader Middle East security developments.'},
    {"name": 'Times of Israel', "url": 'https://www.timesofisrael.com/feed/', "category": 'geopolitics/world news', "type": 'rss', "provides": 'Israel and Middle East news; conflict, security, and regional diplomacy coverage.'},
    {"name": 'UN News - All', "url": 'https://news.un.org/feed/subscribe/en/news/all/rss.xml', "category": 'geopolitics/world news', "type": 'rss', "provides": 'Official United Nations news feed; Security Council, conflicts, humanitarian crises, sanctions, peacekeeping.'},
    {"name": 'ECB Data Portal — EUR/USD reference rate (data-detail-api)', "url": 'https://data.ecb.europa.eu/data-detail-api/EXR.D.USD.EUR.SP00.A', "category": 'macro/econ/government data', "type": 'json', "provides": 'Daily ECB EUR/USD reference exchange rate, keyless JSON. Swap the series key for any ECB SDW series. Central-bank FX anchor.'},
    {"name": 'ECB Data Portal — Main Refinancing Operations policy rate', "url": 'https://data.ecb.europa.eu/data-detail-api/FM.D.U2.EUR.4F.KR.MRR_FR.LEV', "category": 'macro/econ/government data', "type": 'json', "provides": 'ECB main refinancing (policy) rate level, keyless JSON. Direct euro-area monetary-policy rate feed.'},
    {"name": 'ECB Data Portal — euro-area HICP inflation (ANR)', "url": 'https://data.ecb.europa.eu/data-detail-api/ICP.M.U2.N.000000.4.ANR', "category": 'macro/econ/government data', "type": 'json', "provides": 'Euro-area HICP all-items annual rate of change, keyless JSON via ECB series key. Cross-checks Eurostat inflation.'},
    {"name": 'Eurostat — HICP inflation (annual rate, JSON)', "url": 'https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/prc_hicp_manr?format=JSON&lang=EN&geo=EA&time=2024-01', "category": 'macro/econ/government data', "type": 'json', "provides": 'Euro-area HICP annual inflation rate, keyless JSON-stat. Swap dataset code (prc_hicp_manr) for any Eurostat table. EU inflation prints.'},
    {"name": 'Eurostat — euro-area quarterly GDP growth', "url": 'https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/namq_10_gdp?format=JSON&geo=EA20&na_item=B1GQ&unit=CLV_PCH_PRE&s_adj=SCA&time=2024-Q1', "category": 'macro/econ/government data', "type": 'json', "provides": 'Euro-area quarter-on-quarter real GDP growth, keyless JSON-stat. EU growth-cycle signal.'},
    {"name": 'Eurostat — euro-area unemployment rate (SDMX-JSON)', "url": 'https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/une_rt_m?format=JSON&geo=EA20&time=2024-01', "category": 'macro/econ/government data', "type": 'json', "provides": 'Monthly euro-area (EA20) unemployment rate, keyless SDMX 2.1 JSON. EU labour-market macro.'},
    {"name": 'OECD SDMX — Consumer Prices (CPI) data', "url": 'https://sdmx.oecd.org/public/rest/data/OECD.SDD.TPS,DSD_PRICES@DF_PRICES_ALL,1.0/USA.M.N.CPI.PA._T.N.GY?startPeriod=2024-01&format=jsondata', "category": 'macro/econ/government data', "type": 'api', "provides": 'OECD harmonized CPI (here US, monthly, YoY) via the public SDMX REST endpoint, keyless. Vary the country/freq/measure key for cross-OECD inflation comparisons.'},
    {"name": 'TreasuryDirect — auctioned securities API', "url": 'https://www.treasurydirect.gov/TA_WS/securities/auctioned?format=json&days=7', "category": 'macro/econ/government data', "type": 'json', "provides": 'Recently auctioned Treasury securities (bills/notes/bonds) with rates and dates'},
    {"name": 'US BLS Public Data API v2 (CPI series)', "url": 'https://api.bls.gov/publicAPI/v2/timeseries/data/CUUR0000SA0', "category": 'macro/econ/government data', "type": 'json', "provides": 'Keyless BLS timeseries JSON. Series IDs cover CPI (inflation), unemployment, employment (CES/CPS), PPI, earnings. Swap the trailing series ID. Anonymous tier capped at 25 queries/day, no key. Core US inflation/jobs prints that move macro and crypto markets.'},
    {"name": 'US Federal Reserve — H.15 Selected Interest Rates feed', "url": 'https://www.federalreserve.gov/feeds/h15.xml', "category": 'macro/econ/government data', "type": 'rss', "provides": 'H.15 selected interest rates (Treasury yields, fed funds, prime) update feed'},
    {"name": 'US Federal Reserve — all press releases RSS', "url": 'https://www.federalreserve.gov/feeds/press_all.xml', "category": 'macro/econ/government data', "type": 'rss', "provides": 'Fed press releases feed (FOMC statements, policy actions, banking news)'},
    {"name": 'US Federal Reserve — speeches RSS', "url": 'https://www.federalreserve.gov/feeds/speeches.xml', "category": 'macro/econ/government data', "type": 'rss', "provides": 'Fed governor/chair speeches feed (forward-guidance/tone signal)'},
    {"name": 'US Treasury FiscalData — Daily Treasury Statement (avg interest rates)', "url": 'https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v2/accounting/od/avg_interest_rates?page%5Bsize%5D=1', "category": 'macro/econ/government data', "type": 'json', "provides": 'Average interest rates on US Treasury marketable + non-marketable securities by month, keyless JSON. Rate-environment proxy.'},
    {"name": 'US Treasury FiscalData — Debt to the Penny', "url": 'https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v2/accounting/od/debt_to_penny?fields=tot_pub_debt_out_amt,record_date&sort=-record_date&page%5Bsize%5D=1', "category": 'macro/econ/government data', "type": 'json', "provides": 'Daily total US public debt outstanding, JSON, fully keyless. Filterable/sortable REST. Tracks debt-ceiling / fiscal markets.'},
    {"name": 'US Treasury FiscalData — Rates of Exchange', "url": 'https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/rates_of_exchange?page%5Bsize%5D=1', "category": 'macro/econ/government data', "type": 'json', "provides": 'Official US Treasury quarterly FX rates for foreign currencies, keyless JSON. Government-anchored reference rates.'},
    {"name": 'US Treasury — Daily Treasury Yield Curve (XML)', "url": 'https://home.treasury.gov/resource-center/data-chart-center/interest-rates/pages/xml?data=daily_treasury_yield_curve&field_tdr_date_value=2024', "category": 'macro/econ/government data', "type": 'html', "provides": 'Official daily Treasury par yield curve rates as keyless Atom XML'},
    {"name": 'World Bank API — country metadata', "url": 'https://api.worldbank.org/v2/country?format=json&per_page=5', "category": 'macro/econ/government data', "type": 'json', "provides": 'Country/region reference list with income group, region, capital, lat/long. Keyless JSON used to map ISO codes for indicator pulls.'},
    {"name": 'World Bank API — data sources catalog', "url": 'https://api.worldbank.org/v2/sources?format=json', "category": 'macro/econ/government data', "type": 'json', "provides": 'Lists all World Bank databases (WDI, IDS, etc.) with IDs, keyless. Metadata to drive indicator queries programmatically.'},
    {"name": 'World Bank Indicators API (GDP, single country)', "url": 'https://api.worldbank.org/v2/country/US/indicator/NY.GDP.MKTP.CD?format=json&date=2022', "category": 'macro/econ/government data', "type": 'json', "provides": 'Keyless World Bank indicator JSON. ~16k indicators (GDP, inflation FP.CPI.TOTL.ZG, debt, trade) for any ISO country code. Long-run macro panel, no auth.'},
    {"name": 'World Bank Indicators API (global cross-country, paginated)', "url": 'https://api.worldbank.org/v2/country/all/indicator/FP.CPI.TOTL.ZG?format=json&date=2023&per_page=5', "category": 'macro/econ/government data', "type": 'json', "provides": 'Same World Bank API for all-country cross-section of an indicator (here CPI inflation %). Keyless; per_page/date params for bulk macro comparisons.'},
    {"name": 'CoinGecko — global market', "url": 'https://api.coingecko.com/api/v3/global', "category": 'markets', "type": 'json', "provides": 'Total crypto market cap, 24h volume, BTC/ETH dominance, market-cap change %. Regime context for crypto legs.'},
    {"name": 'CoinPaprika — global', "url": 'https://api.coinpaprika.com/v1/global', "category": 'markets', "type": 'json', "provides": 'Global market cap, volume, BTC dominance, market-cap ATH. Alternate regime feed to CoinGecko global.'},
    {"name": 'Business Insider Markets RSS', "url": 'https://markets.businessinsider.com/rss/news', "category": 'markets/commodities', "type": 'rss', "provides": 'Markets-desk news covering stocks, crypto, and commodities. General markets aggregator.'},
    {"name": 'MarketWatch — Market Pulse RSS', "url": 'https://feeds.content.dowjones.io/public/rss/mw_marketpulse', "category": 'markets/commodities', "type": 'rss', "provides": 'Real-time market-moving headlines across equities, commodities, FX. Broad markets aggregator.'},
    {"name": 'Kalshi Public — Events', "url": 'https://r.jina.ai/https://api.elections.kalshi.com/trade-api/v2/events?limit=100&with_nested_markets=true', "category": 'prediction-markets', "type": 'json', "provides": 'Kalshi events with nested markets and category. Maps multi-outcome groupings to individual markets.'},
    {"name": 'Kalshi Public — Exchange Status', "url": 'https://r.jina.ai/https://api.elections.kalshi.com/trade-api/v2/exchange/status', "category": 'prediction-markets', "type": 'json', "provides": 'Exchange/trading open-closed status. Gate to avoid acting on stale quotes when venue is closed.'},
    {"name": 'Kalshi Public — Market Candlesticks', "url": 'https://r.jina.ai/https://api.elections.kalshi.com/trade-api/v2/series/KXELONMARS/markets/KXELONMARS-99/candlesticks?start_ts=1700000000&end_ts=1800000000&period_interval=1440', "category": 'prediction-markets', "type": 'json', "provides": 'Historical OHLC + volume candles per Kalshi market. Backtestable price history with no auth.'},
    {"name": 'Kalshi Public — Markets', "url": 'https://r.jina.ai/https://api.elections.kalshi.com/trade-api/v2/markets?limit=100&status=open', "category": 'prediction-markets', "type": 'json', "provides": 'Kalshi market catalog: ticker, bid/ask, last price, volume, close time, strikes.'},
    {"name": 'Kalshi Public — Series', "url": 'https://r.jina.ai/https://api.elections.kalshi.com/trade-api/v2/series?category=Economics', "category": 'prediction-markets', "type": 'json', "provides": 'Series definitions by category (recurring market families, settlement sources).'},
    {"name": 'Kalshi Public — Trades', "url": 'https://r.jina.ai/https://api.elections.kalshi.com/trade-api/v2/markets/trades?limit=100', "category": 'prediction-markets', "type": 'json', "provides": 'Recent executed Kalshi trades (count, price, side, timestamp, block-trade flag).'},
    {"name": 'Manifold — Bets', "url": 'https://api.manifold.markets/v0/bets?limit=100', "category": 'prediction-markets', "type": 'json', "provides": 'Recent bets across Manifold (amount, prob before/after, outcome, user).'},
    {"name": 'Manifold — Markets', "url": 'https://api.manifold.markets/v0/markets?limit=500', "category": 'prediction-markets', "type": 'json', "provides": 'Manifold market list: question, slug, probability, close time, creator, volume.'},
    {"name": 'Manifold — Search Markets', "url": 'https://api.manifold.markets/v0/search-markets?term=election&limit=50', "category": 'prediction-markets', "type": 'json', "provides": 'Keyword search over Manifold markets returning probability + metadata.'},
    {"name": 'Manifold — Single Market by Slug', "url": 'https://api.manifold.markets/v0/slug/will-trump-win-the-2024-election', "category": 'prediction-markets', "type": 'json', "provides": 'Full single-market detail incl. probability, bets count, answers.'},
    {"name": 'Manifold — Users', "url": 'https://api.manifold.markets/v0/users?limit=100', "category": 'prediction-markets', "type": 'json', "provides": 'User profiles incl. profit/calibration stats. Identify sharp forecasters.'},
    {"name": 'Polymarket CLOB — Markets', "url": 'https://clob.polymarket.com/markets', "category": 'prediction-markets', "type": 'json', "provides": 'CLOB-side market list with token_ids, tick size, min order size, order-book enable flags. Keyless. Bridges conditionId to tradeable token_ids.'},
    {"name": 'Polymarket CLOB — Order Book', "url": 'https://clob.polymarket.com/book?token_id=98022490269692409998126496127597032490334070080325855126491859374983463996227', "category": 'prediction-markets', "type": 'json', "provides": 'Live bid/ask order book for a token_id (price levels + sizes). Keyless. Spread/depth for execution and gap-through modeling.'},
    {"name": 'Polymarket CLOB — Prices History', "url": 'https://r.jina.ai/https://clob.polymarket.com/prices-history?market=98022490269692409998126496127597032490334070080325855126491859374983463996227&interval=max&fidelity=60', "category": 'prediction-markets', "type": 'json', "provides": 'Historical mid-price time series per token_id (interval + fidelity in minutes). Keyless. Backtest price paths and resolution drift.'},
    {"name": 'Polymarket CLOB — Sampling Markets', "url": 'https://clob.polymarket.com/sampling-markets', "category": 'prediction-markets', "type": 'json', "provides": 'Markets currently with active order books (rewards/sampling set). Keyless. Pre-filters to liquid, tradeable markets.'},
    {"name": 'Polymarket Data-API — Holders', "url": 'https://data-api.polymarket.com/holders?market=0x1fad72fae204143ff1c3035e99e7c0f65ea8d5cd9bd1070987bd1a3316f772be&limit=20', "category": 'prediction-markets', "type": 'json', "provides": 'Top token holders per market (proxyWallet, bio, position size). Keyless. Concentration/sharp-money signal.'},
    {"name": 'Polymarket Data-API — Positions', "url": 'https://data-api.polymarket.com/positions?user=0x1615086ace48440b0bc0da28a9dfc3d6e8208f2b', "category": 'prediction-markets', "type": 'json', "provides": 'Open positions per wallet (market, size, avg price, P&L). Copy/whale-watch and per-market exposure.'},
    {"name": 'Polymarket Data-API — Trades (per-wallet)', "url": 'https://data-api.polymarket.com/trades?user=<wallet>&limit=100', "category": 'prediction-markets', "type": 'json', "provides": 'Trade history for a specific wallet (side, asset, conditionId, price, size, timestamp). Requires user=<wallet> param — without it returns an empty list. NOT a global feed. Useful for per-wallet fill history and whale-copy analysis.'},
    {"name": 'Polymarket CLOB — Trades (per-market)', "url": 'https://clob.polymarket.com/trades?market=<token_id>&limit=100', "category": 'prediction-markets', "type": 'json', "provides": 'Per-market fill history from the CLOB (price, size, side, timestamp per match). Requires market=<token_id>. Keyless. Use for realized-fill checks and volume-at-price analysis on a specific token.'},
    {"name": 'Polymarket CLOB — Last Trade Price', "url": 'https://clob.polymarket.com/last-trade-price?token_id=<token_id>', "category": 'prediction-markets', "type": 'json', "provides": 'Lightweight last-fill price and side for a token_id (returns {price, side}). Keyless. Cheaper than a full book pull when only the last-traded price is needed.'},
    {"name": 'Polymarket Data-API — User Portfolio Value', "url": 'https://data-api.polymarket.com/value?user=0x1615086ace48440b0bc0da28a9dfc3d6e8208f2b', "category": 'prediction-markets', "type": 'json', "provides": 'Current USD portfolio value for a wallet. Keyless. Wallet-intelligence sizing of tracked traders.'},
    {"name": 'Polymarket Gamma — Events', "url": 'https://gamma-api.polymarket.com/events?limit=100&active=true&closed=false', "category": 'prediction-markets', "type": 'json', "provides": 'Event-level grouping (multi-market series like elections/seasons), with nested markets. Keyless. Good for mapping related binary legs.'},
    {"name": 'Polymarket Gamma — Markets', "url": 'https://gamma-api.polymarket.com/markets?limit=100&active=true&closed=false', "category": 'prediction-markets', "type": 'json', "provides": 'Full active Polymarket market catalog: question, conditionId, slug, outcomes, outcomePrices, liquidity, volume, start/end dates. Keyless, the canonical metadata feed.'},
    {"name": 'Polymarket Gamma — Single Market by ID', "url": 'https://gamma-api.polymarket.com/markets/540817', "category": 'prediction-markets', "type": 'json', "provides": 'Single market full detail by numeric id. Keyless. Useful for targeted refresh of a tracked market.'},
    {"name": 'Hellenic Shipping News RSS', "url": 'https://www.hellenicshippingnews.com/feed/', "category": 'shipping/commodities', "type": 'rss', "provides": 'Dry-bulk, tanker, freight-rate and commodity-shipping news.'},
    {"name": 'JOC (Journal of Commerce) RSS', "url": 'https://www.joc.com/rssfeed', "category": 'shipping/commodities', "type": 'rss', "provides": 'Container shipping, logistics, and trade-lane news/analysis. Trade-flow disruption signal.'},
    {"name": 'Maritime Executive — articles RSS', "url": 'https://maritime-executive.com/articles.rss', "category": 'shipping/commodities', "type": 'rss', "provides": 'Maritime industry news incl. incidents, sanctions, naval/security events.'},
    {"name": 'Splash247 — shipping news RSS', "url": 'https://splash247.com/feed/', "category": 'shipping/commodities', "type": 'rss', "provides": 'Global shipping markets, freight rates, and sector news.'},
    {"name": 'UN Comtrade — Public Preview API', "url": 'https://r.jina.ai/https://comtradeapi.un.org/public/v1/preview/C/A/HS?reporterCode=842&period=2022&cmdCode=TOTAL&flowCode=X', "category": 'shipping/commodities', "type": 'api', "provides": 'Bilateral merchandise trade flows by HS commodity, reporter/partner, year/month (keyless public preview tier).'},
    {"name": 'gCaptain — maritime news RSS', "url": 'https://gcaptain.com/feed/', "category": 'shipping/commodities', "type": 'rss', "provides": 'Leading maritime/shipping industry news (incidents, port closures, chokepoint events).'},
    {"name": 'ESPN ATP Tennis Scoreboard', "url": 'https://site.api.espn.com/apis/site/v2/sports/tennis/atp/scoreboard', "category": 'sports', "type": 'json', "provides": 'ATP tennis match scores and status (swap atp/wta).'},
    {"name": 'ESPN College Football Scoreboard', "url": 'https://site.api.espn.com/apis/site/v2/sports/football/college-football/scoreboard', "category": 'sports', "type": 'json', "provides": 'NCAAF games, scores, rankings, odds.'},
    {"name": 'ESPN Core API NFL Teams', "url": 'https://sports.core.api.espn.com/v2/sports/football/leagues/nfl/teams', "category": 'sports', "type": 'json', "provides": 'Deeper team entity refs ($ref-linked) for athletes/records/events. Keyless lower-level ESPN API.'},
    {"name": 'ESPN F1 Racing Scoreboard', "url": 'https://site.api.espn.com/apis/site/v2/sports/racing/f1/scoreboard', "category": 'sports', "type": 'json', "provides": 'Formula 1 sessions/race status and standings context.'},
    {"name": 'ESPN MLB Scoreboard', "url": 'https://site.api.espn.com/apis/site/v2/sports/baseball/mlb/scoreboard', "category": 'sports', "type": 'json', "provides": 'Live/scheduled MLB games: scores, inning state, probable pitchers, odds.'},
    {"name": "ESPN Men's College Basketball Scoreboard", "url": 'https://site.api.espn.com/apis/site/v2/sports/basketball/mens-college-basketball/scoreboard', "category": 'sports', "type": 'json', "provides": 'NCAAB games, scores, status, odds.'},
    {"name": 'ESPN NBA Scoreboard', "url": 'https://site.api.espn.com/apis/site/v2/sports/basketball/nba/scoreboard', "category": 'sports', "type": 'json', "provides": 'Live/scheduled NBA games with scores, game state, embedded betting lines.'},
    {"name": 'ESPN NFL News Feed', "url": 'https://site.api.espn.com/apis/site/v2/sports/football/nfl/news', "category": 'sports', "type": 'json', "provides": 'Latest NFL news/headlines as JSON (injuries, roster moves).'},
    {"name": 'ESPN NFL Scoreboard (hidden JSON)', "url": 'https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard', "category": 'sports', "type": 'json', "provides": 'Live & scheduled NFL games: scores, status, clock, odds/spread, teams.'},
    {"name": 'ESPN NFL Standings', "url": 'https://site.api.espn.com/apis/v2/sports/football/nfl/standings', "category": 'sports', "type": 'json', "provides": 'League standings/records (swap sport+league in path).'},
    {"name": 'ESPN NFL Teams List', "url": 'https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams', "category": 'sports', "type": 'json', "provides": 'Team roster of a league with IDs, abbreviations, logos.'},
    {"name": 'ESPN NHL Scoreboard', "url": 'https://site.api.espn.com/apis/site/v2/sports/hockey/nhl/scoreboard', "category": 'sports', "type": 'json', "provides": 'Live/scheduled NHL games with scores and status.'},
    {"name": 'ESPN PGA Golf Scoreboard', "url": 'https://site.api.espn.com/apis/site/v2/sports/golf/pga/scoreboard', "category": 'sports', "type": 'json', "provides": 'PGA tournament leaderboard/round status.'},
    {"name": 'ESPN Soccer Scoreboard (EPL; league-swappable)', "url": 'https://site.api.espn.com/apis/site/v2/sports/soccer/eng.1/scoreboard', "category": 'sports', "type": 'json', "provides": 'Live soccer scores/status with odds; swap eng.1 for other leagues.'},
    {"name": 'ESPN UFC/MMA Scoreboard', "url": 'https://site.api.espn.com/apis/site/v2/sports/mma/ufc/scoreboard', "category": 'sports', "type": 'json', "provides": 'UFC fight cards, results, fight status for fight-night resolution markets.'},
    {"name": 'Jolpica F1 API (Ergast successor) Current Season', "url": 'https://r.jina.ai/https://api.jolpi.ca/ergast/f1/current.json', "category": 'sports', "type": 'json', "provides": 'F1 current-season schedule, results, standings (Ergast-compatible mirror; original ergast.com is dead). Keyless.'},
    {"name": 'Jolpica F1 API Season Results', "url": 'https://r.jina.ai/https://api.jolpi.ca/ergast/f1/2026/results.json', "category": 'sports', "type": 'json', "provides": 'Full race results for a given F1 season with finishing positions. Keyless Ergast-format data.'},
    {"name": 'MLB StatsAPI Schedule', "url": 'https://statsapi.mlb.com/api/v1/schedule?sportId=1', "category": 'sports', "type": 'json', "provides": 'Official MLB schedule with gamePk IDs, status, teams, scores. Fully keyless public MLB API.'},
    {"name": 'MLB StatsAPI Standings', "url": 'https://statsapi.mlb.com/api/v1/standings?leagueId=103,104', "category": 'sports', "type": 'json', "provides": 'Official MLB AL/NL division standings, records, GB. Keyless.'},
    {"name": 'NHL Web API Schedule (now)', "url": 'https://api-web.nhle.com/v1/schedule/now', "category": 'sports', "type": 'json', "provides": 'Current-week NHL schedule with game IDs and times. Keyless official API.'},
    {"name": 'NHL Web API Scores (now)', "url": 'https://api-web.nhle.com/v1/score/now', "category": 'sports', "type": 'json', "provides": 'Current-day NHL scores and live game state from official api-web.nhle.com. Keyless (HTTP->HTTPS redirect).'},
    {"name": 'NHL Web API Standings (now)', "url": 'https://api-web.nhle.com/v1/standings/now', "category": 'sports', "type": 'json', "provides": 'Current NHL standings, points, records. Keyless official API.'},
    {"name": 'OpenLigaDB Bundesliga Matchdata', "url": 'https://api.openligadb.de/getmatchdata/bl1', "category": 'sports', "type": 'json', "provides": 'German Bundesliga (bl1) fixtures and live/final results. Fully open, keyless community sports API.'},
    {"name": 'TheSportsDB All Leagues', "url": 'https://www.thesportsdb.com/api/v1/json/3/all_leagues.php', "category": 'sports', "type": 'json', "provides": "Master list of leagues across all sports with idLeague (use IDs in event lookups). Free public key '3', no signup."},
    {"name": 'TheSportsDB League Table', "url": 'https://www.thesportsdb.com/api/v1/json/3/lookuptable.php?l=4328&s=2025-2026', "category": 'sports', "type": 'json', "provides": "Standings/table for a league+season. Free public key '3'."},
    {"name": 'TheSportsDB Next Events by League', "url": 'https://www.thesportsdb.com/api/v1/json/3/eventsnextleague.php?id=4328', "category": 'sports', "type": 'json', "provides": "Upcoming fixtures for a league (id=4328 is EPL). Dates/teams/IDs for resolution timing. Free key '3'."},
    {"name": 'TheSportsDB Past Events by League', "url": 'https://www.thesportsdb.com/api/v1/json/3/eventspastleague.php?id=4328', "category": 'sports', "type": 'json', "provides": "Recent finished results for a league with final scores. Free key '3', keyless-equivalent."},
    {"name": 'WTO — Latest News RSS', "url": 'https://www.wto.org/library/rss/latest_news_e.xml', "category": 'trade/commodities', "type": 'rss', "provides": 'World Trade Organization news on trade policy, tariffs, and disputes — upstream driver of shipping/commodity trade-flow markets.'},
    {"name": 'Aviation Weather Center METAR API', "url": 'https://aviationweather.gov/api/data/metar?ids=KJFK&format=json', "category": 'weather & natural disaster', "type": 'api', "provides": 'Keyless NOAA AWC METAR/TAF surface obs by airport ICAO.'},
    {"name": 'GDACS Event List API (JSON)', "url": 'https://r.jina.ai/https://www.gdacs.org/gdacsapi/api/events/geteventlist/MAP', "category": 'weather & natural disaster', "type": 'json', "provides": 'GDACS structured JSON event list (severity, coordinates, alert level).'},
    {"name": 'GDACS Global Disaster Alerts RSS', "url": 'https://www.gdacs.org/xml/rss.xml', "category": 'weather & natural disaster', "type": 'rss', "provides": 'Global multi-hazard disaster feed (EQ, TC, flood, volcano, drought) w/ severity.'},
    {"name": 'NASA EONET Categories API', "url": 'https://eonet.gsfc.nasa.gov/api/v3/categories', "category": 'weather & natural disaster', "type": 'api', "provides": 'List of EONET event categories with per-category endpoints.'},
    {"name": 'NASA EONET Events API', "url": 'https://eonet.gsfc.nasa.gov/api/v3/events', "category": 'weather & natural disaster', "type": 'api', "provides": 'NASA natural-event tracker JSON (wildfires, storms, volcanoes, icebergs, etc.).'},
    {"name": 'NOAA NDBC Buoy Latest Observations', "url": 'https://www.ndbc.noaa.gov/data/latest_obs/latest_obs.txt', "category": 'weather & natural disaster', "type": 'html', "provides": 'Latest obs from all NOAA marine buoys (wind, wave, pressure, sea temp) as plain text.'},
    {"name": 'NOAA NHC Tropical Weather Outlook (graphical) RSS', "url": 'https://www.nhc.noaa.gov/gtwo.xml', "category": 'weather & natural disaster', "type": 'rss', "provides": 'NHC 2/7-day tropical cyclone formation outlook (graphical) RSS.'},
    {"name": 'NOAA National Hurricane Center — Atlantic RSS', "url": 'https://www.nhc.noaa.gov/index-at.xml', "category": 'weather & natural disaster', "type": 'rss', "provides": 'NHC Atlantic tropical cyclone advisories/outlooks/tracks as RSS.'},
    {"name": 'NOAA SPC Severe Weather Watches RSS', "url": 'https://www.spc.noaa.gov/products/spcwwrss.xml', "category": 'weather & natural disaster', "type": 'rss', "provides": 'Storm Prediction Center tornado/severe-thunderstorm watch feed.'},
    {"name": 'NOAA Tsunami Warning Center Atom Feed', "url": 'https://www.tsunami.gov/events/xml/PAAQAtom.xml', "category": 'weather & natural disaster', "type": 'rss', "provides": 'National Tsunami Warning Center (US/Canada) Atom feed of tsunami messages/warnings.'},
    {"name": 'NOAA/NWS Active Alerts API', "url": 'https://api.weather.gov/alerts/active', "category": 'weather & natural disaster', "type": 'api', "provides": 'All active US NWS alerts (warnings/watches/advisories) as GeoJSON; filter by area/event.'},
    {"name": 'NOAA/NWS Point Forecast API', "url": 'https://api.weather.gov/gridpoints/TOP/31,80/forecast', "category": 'weather & natural disaster', "type": 'api', "provides": 'Detailed US gridpoint forecast (temp, wind, precip prob, narrative) per resolved lat/lon.'},
    {"name": 'Open-Meteo Air Quality API', "url": 'https://air-quality-api.open-meteo.com/v1/air-quality?latitude=40&longitude=-74&hourly=pm2_5,pm10,us_aqi', "category": 'weather & natural disaster', "type": 'api', "provides": 'Keyless global air quality (PM2.5, PM10, US AQI) by lat/lon'},
    {"name": 'Open-Meteo Flood API (GloFAS river discharge)', "url": 'https://flood-api.open-meteo.com/v1/flood?latitude=40&longitude=-74&daily=river_discharge', "category": 'weather & natural disaster', "type": 'api', "provides": 'Daily river-discharge forecast (GloFAS) by lat/lon — flood-risk signal'},
    {"name": 'Open-Meteo Forecast API', "url": 'https://api.open-meteo.com/v1/forecast?latitude=40.71&longitude=-74.01&current=temperature_2m&hourly=temperature_2m,precipitation,wind_speed_10m', "category": 'weather & natural disaster', "type": 'api', "provides": 'Free keyless global weather forecast (temp, precip, wind) by lat/lon'},
    {"name": 'Open-Meteo Historical Archive API', "url": 'https://archive-api.open-meteo.com/v1/archive?latitude=40&longitude=-74&start_date=2024-01-01&end_date=2024-01-02&daily=temperature_2m_max,temperature_2m_min,precipitation_sum', "category": 'weather & natural disaster', "type": 'api', "provides": 'Reanalysis historical weather (ERA5) back to 1940 by lat/lon'},
    {"name": 'Open-Meteo Marine API', "url": 'https://marine-api.open-meteo.com/v1/marine?latitude=54&longitude=8&hourly=wave_height,wave_period,swell_wave_height', "category": 'weather & natural disaster', "type": 'api', "provides": 'Wave height, period, swell, ocean conditions by lat/lon'},
    {"name": 'Smithsonian GVP Weekly Volcanic Activity RSS', "url": 'https://volcano.si.edu/news/WeeklyVolcanoRSS.xml', "category": 'weather & natural disaster', "type": 'rss', "provides": 'Smithsonian GVP weekly report of new/ongoing volcanic eruptions and unrest.'},
    {"name": 'USGS Earthquakes — All (past day) GeoJSON', "url": 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson', "category": 'weather & natural disaster', "type": 'json', "provides": 'Real-time GeoJSON of all earthquakes worldwide past 24h'},
    {"name": 'USGS Earthquakes — Significant (past week) GeoJSON', "url": 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.geojson', "category": 'weather & natural disaster', "type": 'json', "provides": 'GeoJSON of significant earthquakes past 7 days'},
    {"name": 'USGS FDSN Event Query (custom earthquake search)', "url": 'https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&starttime=2024-01-01&endtime=2024-01-02&minmagnitude=4', "category": 'weather & natural disaster', "type": 'api', "provides": 'Parameterized earthquake query API (date/magnitude/bbox), GeoJSON/CSV/quakeml'},
    {"name": 'USGS Water Services — Instantaneous Values', "url": 'https://waterservices.usgs.gov/nwis/iv/?format=json&sites=01646500&parameterCd=00060', "category": 'weather & natural disaster', "type": 'api', "provides": 'Real-time US streamflow/gage-height by USGS site number; flood-stage monitoring.'},

    # ── India law (vetted 2026-06-27) ───────────────────────────────────────
    # NOTE: Most Indian govt law portals (RBI, SEBI, MCA, SEBI, CCI, eGazette,
    # eCourts API, IP India, AdvocateKhoj) are JS-gated, CDN-blocked, or form-
    # gated — NOT usable without a browser session. Only the sources below are
    # confirmed keyless via live curl probe.
    {"name": 'India Penal Code JSON (IPC)', "url": 'https://raw.githubusercontent.com/civictech-India/Indian-Law-Penal-Code-Json/main/ipc.json', "category": 'india law', "type": 'json', "provides": '575 IPC sections as JSON: {chapter, section, section_title, section_desc}. Static, keyless.'},
    {"name": 'India CrPC JSON', "url": 'https://raw.githubusercontent.com/civictech-India/Indian-Law-Penal-Code-Json/main/crpc.json', "category": 'india law', "type": 'json', "provides": '525 CrPC sections as JSON: {chapter, section, section_title, section_desc}. Static, keyless.'},
    {"name": 'India CPC JSON', "url": 'https://raw.githubusercontent.com/civictech-India/Indian-Law-Penal-Code-Json/main/cpc.json', "category": 'india law', "type": 'json', "provides": '171 CPC (Civil Procedure Code) sections as JSON: {section, title, description}. Static, keyless.'},
    {"name": 'India Evidence Act JSON', "url": 'https://raw.githubusercontent.com/civictech-India/Indian-Law-Penal-Code-Json/main/iea.json', "category": 'india law', "type": 'json', "provides": '184 Indian Evidence Act sections as JSON. Static, keyless.'},
    {"name": 'India Hindu Marriage Act JSON', "url": 'https://raw.githubusercontent.com/civictech-India/Indian-Law-Penal-Code-Json/main/hma.json', "category": 'india law', "type": 'json', "provides": '283 Hindu Marriage Act sections as JSON. Static, keyless.'},
    {"name": 'India Motor Vehicles Act JSON', "url": 'https://raw.githubusercontent.com/civictech-India/Indian-Law-Penal-Code-Json/main/MVA.json', "category": 'india law', "type": 'json', "provides": 'Motor Vehicles Act sections as JSON. Static, keyless.'},
    {"name": 'India NIA Act JSON', "url": 'https://raw.githubusercontent.com/civictech-India/Indian-Law-Penal-Code-Json/main/nia.json', "category": 'india law', "type": 'json', "provides": 'National Investigation Agency Act sections as JSON. Static, keyless.'},
    {"name": 'IndianKanoon case law search (HTML scrape)', "url": 'https://indiankanoon.org/search/?formInput=section+302+IPC&pagenum=0', "category": 'india law', "type": 'html', "provides": '1.4M+ Indian court judgments and acts; search by query. Keyless HTML. Respect rate limits — no aggressive crawling.'},
    {"name": 'PRS India Bills Tracker', "url": 'https://prsindia.org/billtrack', "category": 'india law', "type": 'html', "provides": '968+ Parliamentary bill links (all sessions); scrapeable HTML. No JSON API. Filter by category/session from the page.'},
]

def categories():
    c = {}
    for s in SOURCES:
        c[s["category"]] = c.get(s["category"], 0) + 1
    return dict(sorted(c.items()))

def by_category(cat):
    cat = cat.lower()
    return [s for s in SOURCES if cat in s["category"].lower()]

def find(q):
    q = q.lower()
    return [s for s in SOURCES if q in s["name"].lower() or q in s["url"].lower() or q in s["provides"].lower()]

def fetch(name_or_url, timeout=10):
    """Keyless GET. Accepts a source name, a substring, or a full URL. Returns bytes."""
    url = name_or_url
    if not name_or_url.startswith("http"):
        hits = find(name_or_url)
        if not hits:
            raise KeyError("no source matches %r" % name_or_url)
        url = hits[0]["url"]
    hdrs = {"User-Agent": "polymarket-bot/1.0 (keyless)"}
    if "r.jina.ai" in url:
        hdrs["X-Respond-With"] = "text"   # jina reader: raw passthrough, not markdown-wrapped
    req = urllib.request.Request(url, headers=hdrs)
    try:
        return urllib.request.urlopen(req, timeout=timeout).read()
    except Exception:
        # Some sources UA-gate the bot UA (Business Insider RSS, Treasury yield-curve XML)
        # and refuse / hang on it. Retry once with a browser UA before giving up.
        bhdrs = dict(hdrs)
        bhdrs["User-Agent"] = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                               "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36")
        breq = urllib.request.Request(url, headers=bhdrs)
        return urllib.request.urlopen(breq, timeout=timeout).read()

if __name__ == "__main__":
    print("%d keyless data sources across %d categories\n" % (len(SOURCES), len(categories())))
    for cat, n in categories().items():
        print("  %3d  %s" % (n, cat))
