#!/usr/bin/env python3
"""
datagen_report.py — autonomous OFFLINE analyst.

Builds a fresh, keyless, real daily series (BTC / ETH / Nasdaq Composite), runs the
DATAGEN multi-agent pipeline on the FREE NVIDIA 70B (meta/llama-3.3-70b-instruct,
$0), and mirrors its generated report + plots into the Obsidian vault.

HONESTY / project discipline (overrides any temptation to "use the number"):
  - DESCRIPTIVE research only. NEVER a trade signal, never an input to entries.
    The free LLM is miscalibrated for conviction (compresses p to 0.2-0.55, can't
    price tails — candela_args finding) and LLM-driven analysis is the documented
    dead-end pattern (Strategy Graveyard / calibrated mids). This note is a data
    narrative, full stop.
  - Paper/research only. Indices are not the bot's tradeable venue (Polymarket).

Wiring: launchd com.aryan.datagen-report (weekly). Logs to /tmp (exit-78 lesson).
Reuses market_history.py's keyless fetchers (stdlib-only). The DATAGEN run itself is
invoked via its own .venv python as a subprocess.
"""
import os, sys, csv, glob, shutil, subprocess
from datetime import datetime, timezone, timedelta

POLY    = os.path.expanduser("~/Documents/polymarket")
DATAGEN = os.path.expanduser("~/Documents/oss-bots/DATAGEN")
DATA    = os.path.join(DATAGEN, "data")
VENV_PY = os.path.join(DATAGEN, ".venv/bin/python")
CSV_PATH = os.path.join(DATA, "OnlineSalesData.csv")

VAULT   = os.path.expanduser("~/Documents/PolymarketVault")
REPORTS = os.path.join(VAULT, "Reports")
ATTACH  = os.path.join(REPORTS, "datagen")          # plot attachments
NOTE    = os.path.join(REPORTS, "DATAGEN Market Report.md")

CAP_SECONDS = 1000   # DATAGEN's quality-loop doesn't self-terminate; artifacts land well before this

sys.path.insert(0, POLY)


def _to_date(ts_seconds):
    return datetime.fromtimestamp(ts_seconds, tz=timezone.utc).date().isoformat()


def build_csv():
    """Fetch BTC/ETH (Binance) + Nasdaq Composite, align on common UTC dates, drop NaN."""
    import market_history as mh
    btc = {_to_date(t): v for t, v in (mh.hist_crypto("BTCUSDT") or [])}
    eth = {_to_date(t): v for t, v in (mh.hist_crypto("ETHUSDT") or [])}
    today = datetime.now(timezone.utc).date()
    start = (today - timedelta(days=130)).isoformat()
    nas = {_to_date(t): v for t, v in (mh.get_hist("nasdaq", "COMP", start, today.isoformat()) or [])}

    dates = sorted(set(btc) & set(eth) & set(nas))
    rows = [(d, btc[d], eth[d], nas[d]) for d in dates]
    if len(rows) < 20:
        raise SystemExit(f"[datagen_report] too few aligned rows ({len(rows)}) — sources may be blocked; aborting.")

    os.makedirs(DATA, exist_ok=True)
    with open(CSV_PATH, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["date", "Bitcoin", "Ether", "Nasdaq"])
        w.writerows(rows)
    return len(rows), (dates[0], dates[-1])


def run_datagen():
    """Clear prior outputs, run DATAGEN headless on the free 70B (hard time cap)."""
    for p in glob.glob(os.path.join(DATA, "*")):
        if os.path.basename(p) != "OnlineSalesData.csv":
            try:
                os.remove(p)
            except OSError:
                pass
    env = dict(os.environ, MPLBACKEND="Agg")
    cmd = ["perl", "-e", "alarm %d; exec @ARGV" % CAP_SECONDS, VENV_PY, "-u", "main.py"]
    with open("/tmp/datagen_report_run.log", "w") as log:
        subprocess.run(cmd, cwd=DATAGEN, env=env, stdin=subprocess.DEVNULL,
                       stdout=log, stderr=subprocess.STDOUT)


def harvest(n_rows, rng):
    """Copy report.md + plots into the vault as an explicitly-offline note."""
    os.makedirs(ATTACH, exist_ok=True)
    rpath = os.path.join(DATA, "report.md")
    body = open(rpath).read().strip() if os.path.exists(rpath) else "_(no report.md produced this run — DATAGEN hit its iteration cap before writing one)_"

    pngs = []
    for p in sorted(glob.glob(os.path.join(DATA, "*.png"))):
        name = os.path.basename(p)
        shutil.copy2(p, os.path.join(ATTACH, name))
        pngs.append(name)
    embeds = "\n".join(f"![[Reports/datagen/{name}]]" for name in pngs) or "_(no plots produced this run)_"

    today = datetime.now(timezone.utc).date().isoformat()
    note = f"""---
type: report
generated_by: datagen
updated: {today}
tags:
  - datagen
  - markets
  - offline-analyst
---

# DATAGEN Market Report — {today}

> [!warning] OFFLINE descriptive analysis only — **NOT a trade signal.**
> Auto-generated by the DATAGEN multi-agent pipeline (see [[External Tools Vetted]])
> on the FREE NVIDIA 70B, over a fresh keyless BTC/ETH/Nasdaq daily series
> ({n_rows} trading days, {rng[0]} → {rng[1]}). The free LLM is miscalibrated for
> conviction and LLM-driven analysis is a documented dead end ([[Strategy Graveyard]]) —
> read this as a data narrative, never as an edge. Indices are not the bot's venue.

## Plots
{embeds}

## Report
{body}
"""
    with open(NOTE, "w") as f:
        f.write(note)
    return len(pngs), os.path.exists(rpath)


def main():
    n, rng = build_csv()
    print(f"[datagen_report] built CSV: {n} rows {rng[0]}->{rng[1]}", flush=True)
    run_datagen()
    n_png, had_report = harvest(n, rng)
    print(f"[datagen_report] vault note written: {NOTE} ({n_png} plots, report={had_report})", flush=True)


if __name__ == "__main__":
    main()
