#!/usr/bin/env python3
"""
newsnow_obsidian.py — pull trending news from local newsnow instance → Obsidian vault
Writes: PolymarketVault/Reports/News Feed.md
Run: python3 newsnow_obsidian.py
Requires: newsnow dev server running at localhost:5173
"""

import json
import urllib.request
import urllib.error
from datetime import datetime
from pathlib import Path

NEWSNOW_BASE = "http://localhost:5173/api/s"
VAULT_PATH = Path.home() / "Documents/PolymarketVault/Reports/News Feed.md"

# Sources to pull — ordered by relevance
SOURCES = [
    ("hackernews",            "Hacker News"),
    ("github",                "GitHub Trending"),
    ("producthunt",           "Product Hunt"),
    ("github-trending-today", "GitHub Trending Today"),
    ("36kr",                  "36Kr (China Tech)"),
    ("wallstreetcn-hot",      "Wall St CN Hot"),
    ("cls-telegraph",         "财联社 Telegraph"),
    ("aihot",                 "AI Hot"),
    ("v2ex",                  "V2EX"),
]

MAX_ITEMS = 10  # items per source


def fetch_source(source_id: str) -> list[dict]:
    url = f"{NEWSNOW_BASE}?id={source_id}"
    try:
        with urllib.request.urlopen(url, timeout=8) as r:
            data = json.loads(r.read())
        if data.get("status") in ("success", "cache"):
            return data.get("items", [])[:MAX_ITEMS]
    except Exception as e:
        print(f"  [SKIP] {source_id}: {e}")
    return []


def build_markdown(results: dict[str, list[dict]]) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "---",
        "type: news-feed",
        f"updated: {now}",
        "status: fresh",
        "tags: [news, trending, auto]",
        "---",
        "",
        f"# News Feed — {now}",
        "",
        "> Auto-generated by newsnow_obsidian.py from local newsnow instance.",
        "",
    ]

    for source_id, label in SOURCES:
        items = results.get(source_id, [])
        if not items:
            continue
        lines.append(f"## {label}")
        lines.append("")
        for item in items:
            title = item.get("title", "").strip()
            url = item.get("url", "")
            extra = item.get("extra", {}) or {}
            info = extra.get("info", "") or extra.get("star", "") or ""
            suffix = f" `{info}`" if info else ""
            if url:
                lines.append(f"- [{title}]({url}){suffix}")
            else:
                lines.append(f"- {title}{suffix}")
        lines.append("")

    return "\n".join(lines)


def mark_stale():
    """newsnow unreachable → make the staleness LOUD instead of leaving a
    silently-old note (Aryan's rule: silence != success). Preserves the
    last-good body; only flips the frontmatter and injects a visible callout."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    callout = (
        f"> [!warning] STALE — newsnow unreachable as of {now}.\n"
        f"> Below is the last successful pull. Check the service: "
        f"`launchctl list | grep newsnow` / `/tmp/newsnow.err`.\n"
    )

    if not VAULT_PATH.exists():
        VAULT_PATH.parent.mkdir(parents=True, exist_ok=True)
        VAULT_PATH.write_text(
            "---\ntype: news-feed\n"
            f"updated: never\nstatus: STALE\nlast_attempt: {now}\n"
            "tags: [news, trending, auto]\n---\n\n"
            f"# News Feed — STALE\n\n{callout}\n"
            "> No successful pull yet. newsnow has never been reachable.\n"
        )
        print(f"  [STALE] no prior note — wrote placeholder → {VAULT_PATH}")
        return

    text = VAULT_PATH.read_text()
    # Strip any prior STALE callout so they don't stack on repeated failures.
    body = text
    if body.startswith("---\n"):
        end = body.find("\n---\n", 4)
        if end != -1:
            fm, rest = body[4:end], body[end + 5:]
            # rewrite frontmatter keys
            fm_lines, seen = [], set()
            for ln in fm.splitlines():
                key = ln.split(":", 1)[0].strip()
                if key == "status":
                    fm_lines.append("status: STALE"); seen.add("status")
                elif key == "last_attempt":
                    fm_lines.append(f"last_attempt: {now}"); seen.add("last_attempt")
                else:
                    fm_lines.append(ln)
            if "status" not in seen:
                fm_lines.append("status: STALE")
            if "last_attempt" not in seen:
                fm_lines.append(f"last_attempt: {now}")
            # drop a previously-injected callout block (lines starting "> ")
            rest_lines = rest.splitlines()
            cleaned, skipping = [], False
            for ln in rest_lines:
                if ln.startswith("> [!warning] STALE"):
                    skipping = True
                    continue
                if skipping and (ln.startswith("> ") or ln.strip() == ""):
                    if ln.startswith("> "):
                        continue
                    skipping = False
                cleaned.append(ln)
            rest_clean = "\n".join(cleaned).lstrip("\n")
            # inject fresh callout right after the H1 if present, else at top
            out_lines = rest_clean.splitlines()
            insert_at = 0
            for i, ln in enumerate(out_lines):
                if ln.startswith("# "):
                    insert_at = i + 1
                    break
            out_lines.insert(insert_at, "")
            out_lines.insert(insert_at + 1, callout)
            body = "---\n" + "\n".join(fm_lines) + "\n---\n" + "\n".join(out_lines)
    VAULT_PATH.write_text(body)
    print(f"  [STALE] flipped note to STALE + callout → {VAULT_PATH}")


def main():
    print(f"[newsnow→obsidian] {datetime.now().strftime('%H:%M:%S')}")
    results = {}
    for source_id, label in SOURCES:
        items = fetch_source(source_id)
        results[source_id] = items
        print(f"  {label}: {len(items)} items")

    total = sum(len(v) for v in results.values())
    if total == 0:
        print("  [WARN] No items fetched — is newsnow running? (pnpm dev in oss-bots/newsnow)")
        mark_stale()
        return

    md = build_markdown(results)
    VAULT_PATH.parent.mkdir(parents=True, exist_ok=True)
    VAULT_PATH.write_text(md)
    print(f"  Written → {VAULT_PATH} ({total} items)")


if __name__ == "__main__":
    main()
